spring:
  #数据源
  datasource:
    url: jdbc:mysql://116.62.226.77:8888/hospital_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传最大尺寸
  servlet:
    multipart:
      max-file-size: 5MB
  cache:
    type: redis
  redis:
    database: 0
    host: 116.62.226.77
    port: 6379
    # 有密码填密码，没有密码不填
    password:
    # 连接超时时间（ms)
    timeout: 1000
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0

#mybatis配置
mybatis:
  typeAliasesPackage: top.lsyweb.hosadm.domain
  mapperLocations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 将sql语句打印到控制台
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #configLocation: classpath:/mybatis-config.xml