spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 720519
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传最大尺寸
  servlet:
    multipart:
      max-file-size: 5MB

#mybatis配置
mybatis:
  typeAliasesPackage: top.lsyweb.hosadm.domain
  mapperLocations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 将sql语句打印到控制台
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #configLocation: classpath:/mybatis-config.xml